name: EMBL_training
channels:
  - conda-forge
  - defaults
  - rapidsai
dependencies:
  - python=3.9
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - dask-image
  - cucim
  - cudatoolkit=11.7
  - scikit-image
  - pip
  - pip:
      - microaligner
      - trackpy
      - shapely
      - cellpose
      - napari
      - openpyxl

      - setuptools
      - pdbpp
      - torch
      - torchvision
      - pyro-ppl
      - jupyter_http_over_ws
      - scipy
      - tifffile
      - imagecodecs
      - zarr
      - aicsimageio
      - fire
      - ome-zarr
      - numba

      - opencv-python-headless==4.6.0.66
      - scanpy
      - leidenalg
